version: "3"

services:
  backend:
    build: ./backend
    image: pariks18/backend
    ports:
      - "5000:5000"
    container_name: backend_container
    environment:
      - NODE_ENV=production
    

  frontend:
    build: ./frontend/roomzy_frontend
    image: pariks18/frontend
    ports:
      - "3000:80"
    container_name: frontend_container
    depends_on:
      - backend
